-- Generated by `npm run seed:corpus`. Do not edit by hand.
--
-- The assistant's corpus: the copy already published on our own pages, chunked by
-- section so a citation can name one. Written from the dictionary, which *is* the
-- source of that text, so this file cannot say something a reader does not see.
--
-- Without it a new database starts with an empty index, and the assistant then
-- answers every question about how the product works with "nothing is indexed yet".
-- That is honest but useless, and it is the state the cloud project was actually in
-- until it was noticed.
--
-- 48 chunks (24 fr, 24 en).
--
-- The NOTES directory is deliberately absent, here as everywhere: those are internal
-- engineering notes and this table is readable by anyone, so seeding them would
-- publish them.

insert into public.ai_documents (source_path, title, heading, anchor, locale, content)
values
  ('/fr/methodology', 'Méthodologie', 'Ce que nous calculons', '#ce-que-nous-calculons', 'fr', 'Un classement des zones d''une ville selon vos priorités, à partir d''indicateurs officiels normalisés à l''intérieur de la ville choisie.'),
  ('/fr/methodology', 'Méthodologie', 'Ce que nous ne calculons pas', '#ce-que-nous-ne-calculons-pas', 'fr', 'Aucun « meilleur quartier » absolu, aucune garantie de sécurité, de place en crèche ou de prix exact d''un logement précis.'),
  ('/fr/methodology', 'Méthodologie', 'Niveaux géographiques', '#niveaux-geographiques', 'fr', 'IRIS quand c''est possible, sinon commune. Le niveau réel est toujours affiché. Une zone IRIS est appelée « zone analysée ».'),
  ('/fr/methodology', 'Méthodologie', 'Fiabilité des données', '#fiabilite-des-donnees', 'fr', 'Chaque zone reçoit un niveau de fiabilité (solides, partielles, limitées, indisponibles) selon la couverture des indicateurs que vous avez jugés importants.'),
  ('/fr/methodology', 'Méthodologie', 'Pondération', '#ponderation', 'fr', 'Vos priorités (de « pas important » à « essentiel ») deviennent des poids. Seuls les thèmes qui comptent pour vous pèsent dans le score.'),
  ('/fr/methodology', 'Méthodologie', 'Données manquantes', '#donnees-manquantes', 'fr', 'Une donnée absente n''est jamais remplacée par zéro : elle réduit la fiabilité et est signalée.'),
  ('/fr/methodology', 'Méthodologie', 'Ne pas mélanger les indicateurs', '#ne-pas-melanger-les-indicateurs', 'fr', 'Salaire, revenu médian, loyer et prix d''achat sont des mesures distinctes, avec des méthodes et des précisions différentes.'),
  ('/fr/privacy', 'Politique de confidentialité', '1. Qui est responsable de vos données', '#1-qui-est-responsable-de-vos-donnees', 'fr', 'Le responsable du traitement est Sergiy Mirochnyk, personne physique, éditeur du site WhereWise. Le projet n''a pas d''activité commerciale et n''est pas tenu de désigner un délégué à la protection des données ; les demandes sont traitées directement par l''éditeur.'),
  ('/fr/privacy', 'Politique de confidentialité', '2. Ce que nous traitons, pourquoi, et sur quel fondement', '#2-ce-que-nous-traitons-pourquoi-et-sur-quel-fondement', 'fr', 'Le RGPD impose d''indiquer, pour chaque usage, la donnée concernée et la base légale qui l''autorise. Le tableau ci-dessous les reprend une par une.
Lancer une simulation sans compte — Ville, quartier, loyer, salaire, composition du foyer, déplacements — Produire le résultat que vous demandez — Intérêt légitime : sans ces réponses il n''y a rien à calculer. Elles restent dans votre navigateur.
Calculer l''impôt et les prestations — Salaire, loyer, nombre d''enfants, code commune — Interroger OpenFisca, le moteur de règles socio-fiscales public — Intérêt légitime. Aucun identifiant n''est transmis : ni nom, ni e-mail, ni adresse.
Créer un compte — Adresse e-mail, prénom, nom, ville de résidence — Vous identifier et vous permettre de revenir — Exécution du service que vous demandez en créant le compte.
Enregistrer une simulation — Le contenu de la simulation, y compris salaire et loyer — La retrouver plus tard — Exécution du service, sur votre demande expresse. Rien n''est enregistré sans un clic de votre part.
Sécurité et bon fonctionnement — Journaux techniques de l''hébergeur, dont l''adresse IP — Détecter les pannes et les abus — Intérêt légitime à faire fonctionner le service.'),
  ('/fr/privacy', 'Politique de confidentialité', '3. Ce que nous ne faisons pas', '#3-ce-que-nous-ne-faisons-pas', 'fr', 'Cette liste est aussi importante que la précédente, et elle est vérifiable : le code du site est écrit sans aucune de ces briques.
Aucun traceur publicitaire, aucun outil de mesure d''audience, aucun pixel de réseau social.
Aucune revente, location ou partage de vos données à des fins commerciales.
Aucun profilage et aucune décision automatisée produisant des effets juridiques : nos résultats sont indicatifs.
Aucune donnée sensible au sens de l''article 9 du RGPD : ni santé, ni origine, ni opinion, ni donnée bancaire.
Aucune adresse postale précise : le calcul s''arrête au quartier.'),
  ('/fr/privacy', 'Politique de confidentialité', '4. Qui d''autre voit ces données', '#4-qui-d-autre-voit-ces-donnees', 'fr', 'Trois prestataires interviennent, et aucun ne reçoit plus que ce qui est nécessaire à son rôle.
Supabase — Comptes et simulations enregistrées — Base de données et authentification — Serveurs à Paris (eu-west-3). Sous-traitant au sens de l''article 28.
Vercel — Requêtes du site, journaux techniques — Hébergement du site et des fonctions serveur — Fonctions serveur exécutées à Paris (cdg1). Le réseau de diffusion est mondial ; les transferts éventuels sont encadrés par les clauses contractuelles types.
OpenFisca France — Salaire, loyer, nombre d''enfants, code commune — sans aucun identifiant — Calculer l''impôt sur le revenu et les prestations — Moteur de règles public. Les données envoyées ne permettent pas de vous identifier.'),
  ('/fr/privacy', 'Politique de confidentialité', '5. Combien de temps nous les gardons', '#5-combien-de-temps-nous-les-gardons', 'fr', 'Une donnée que l''on garde sans raison est une donnée que l''on finit par perdre. Les durées sont donc courtes et liées à un usage.
Simulation lancée sans compte — Jusqu''à ce que vous vidiez le stockage de votre navigateur — Elle ne quitte jamais votre appareil — Vous pouvez l''effacer à tout moment depuis les réglages de votre navigateur.
Compte et profil — Tant que le compte existe — Vous permettre de revenir — Supprimé sur demande, avec tout ce qui s''y rattache.
Simulations enregistrées — Tant que vous les conservez — Les relire et les comparer — Supprimables une par une depuis votre compte, immédiatement et définitivement.
Journaux techniques — Quelques semaines chez l''hébergeur — Sécurité et diagnostic — Durées fixées par l''hébergeur, non exploitées par nous à d''autres fins.'),
  ('/fr/privacy', 'Politique de confidentialité', '6. Cookies et stockage local', '#6-cookies-et-stockage-local', 'fr', 'Il n''y a pas de bandeau de consentement sur ce site, et ce n''est pas un oubli : seuls des éléments strictement nécessaires sont déposés, ce qui en dispense au titre de l''article 82 de la loi Informatique et Libertés.
Cookie de session — Déposé uniquement si vous vous connectez — Vous garder connecté d''une page à l''autre — Strictement nécessaire. Disparaît à la déconnexion.
Stockage local du navigateur — Brouillon de simulation, langue choisie — Ne pas vous faire ressaisir vos réponses — Reste sur votre appareil, jamais envoyé à un serveur tant que vous n''enregistrez pas.'),
  ('/fr/privacy', 'Politique de confidentialité', '7. Vos droits', '#7-vos-droits', 'fr', 'Vous disposez d''un droit d''accès, de rectification, d''effacement, de limitation, d''opposition et de portabilité sur vos données. Deux de ces droits s''exercent directement dans l''interface, sans nous écrire : votre compte affiche tout ce qu''il contient, et chaque simulation enregistrée se supprime d''un clic. Pour les autres, écrivez-nous : nous répondons sous un mois.'),
  ('/fr/privacy', 'Politique de confidentialité', '8. Réclamation', '#8-reclamation', 'fr', 'Si une réponse ne vous satisfait pas, vous pouvez saisir la Commission nationale de l''informatique et des libertés : CNIL, 3 place de Fontenoy, TSA 80715, 75334 Paris Cedex 07, ou en ligne sur cnil.fr.'),
  ('/fr/privacy', 'Politique de confidentialité', '9. Sécurité', '#9-securite', 'fr', 'Les échanges sont chiffrés en transit. L''accès aux données est cloisonné en base par des politiques qui vérifient, à chaque lecture et à chaque écriture, que la ligne appartient bien à la personne connectée — l''identifiant du compte n''est jamais lu depuis la requête, mais du cookie de session. Aucun mot de passe n''est stocké : la connexion se fait par un lien à usage unique envoyé par e-mail.'),
  ('/fr/privacy', 'Politique de confidentialité', '10. Modifications', '#10-modifications', 'fr', 'Cette politique peut évoluer avec le service. La date en tête de page indique la dernière version ; les changements substantiels seront signalés sur le site.'),
  ('/fr/sources', 'Sources', 'insee_bpe', '#insee_bpe', 'fr', 'Ce que cette source ne dit pas (insee_bpe) : Recense la présence d''un équipement, pas sa qualité, sa capacité ni ses horaires. Une école comptée peut être pleine.'),
  ('/fr/sources', 'Sources', 'dvf', '#dvf', 'fr', 'Ce que cette source ne dit pas (dvf) : Ce qui s''est vendu, pas ce qui est en vente. Les zones à trop peu de transactions sont masquées pour préserver le secret statistique.'),
  ('/fr/sources', 'Sources', 'carte_loyers', '#carte_loyers', 'fr', 'Ce que cette source ne dit pas (carte_loyers) : Loyers d''annonce, pas des loyers réellement payés, et à l''échelle de la commune : l''indicateur ne descend pas au quartier.'),
  ('/fr/sources', 'Sources', 'education_nationale', '#education_nationale', 'fr', 'Ce que cette source ne dit pas (education_nationale) : Liste les établissements et leur adresse. Ne dit rien de la sectorisation ni de vos chances d''y obtenir une place.'),
  ('/fr/sources', 'Sources', 'apl', '#apl', 'fr', 'Ce que cette source ne dit pas (apl) : Mesure une offre de médecins face à une demande, à l''échelle communale. Ce n''est pas une garantie de rendez-vous.'),
  ('/fr/sources', 'Sources', 'delinquance', '#delinquance', 'fr', 'Ce que cette source ne dit pas (delinquance) : Faits enregistrés par la police et la gendarmerie : dépend autant du dépôt de plainte et de l''activité des services que de ce qui s''est réellement produit.'),
  ('/fr/coverage', 'Couverture', 'Couverture', null, 'fr', 'Où WhereWise dispose de données suffisantes, et où les résultats restent au niveau communal.
Villes pilotes — Couverture par zone (IRIS) pour la V1.
Couverture limitée — Résultats au niveau communal uniquement.'),
  ('/en/methodology', 'Methodology', 'What we calculate', '#what-we-calculate', 'en', 'A ranking of a city''s areas by your priorities, from official indicators normalised within the chosen city.'),
  ('/en/methodology', 'Methodology', 'What we do not calculate', '#what-we-do-not-calculate', 'en', 'No absolute ''best neighbourhood'', no guarantee of safety, of a crèche place, or of the exact price of a specific home.'),
  ('/en/methodology', 'Methodology', 'Geographic levels', '#geographic-levels', 'en', 'IRIS where possible, otherwise commune. The real level is always shown. An IRIS zone is called an ''analysed area''.'),
  ('/en/methodology', 'Methodology', 'Data confidence', '#data-confidence', 'en', 'Each area gets a confidence level (strong, partial, limited, unavailable) based on the coverage of the indicators you marked important.'),
  ('/en/methodology', 'Methodology', 'Weighting', '#weighting', 'en', 'Your priorities (from ''not important'' to ''critical'') become weights. Only the themes that matter to you count toward the score.'),
  ('/en/methodology', 'Methodology', 'Missing data', '#missing-data', 'en', 'A missing value is never replaced with zero: it lowers confidence and is flagged.'),
  ('/en/methodology', 'Methodology', 'Don''t mix indicators', '#don-t-mix-indicators', 'en', 'Salary, median income, rent and purchase price are distinct measures with different methods and precision.'),
  ('/en/privacy', 'Privacy policy', '1. Who is responsible for your data', '#1-who-is-responsible-for-your-data', 'en', 'The data controller is Sergiy Mirochnyk, a natural person and the publisher of WhereWise. The project has no commercial activity and is not required to appoint a data protection officer; requests are handled by the publisher directly.'),
  ('/en/privacy', 'Privacy policy', '2. What we process, why, and on what basis', '#2-what-we-process-why-and-on-what-basis', 'en', 'The GDPR requires each use to state the data involved and the legal basis that allows it. The table below takes them one at a time.
Running a simulation without an account — City, district, rent, salary, household, travel — Producing the result you asked for — Legitimate interest: without these answers there is nothing to compute. They stay in your browser.
Computing tax and benefits — Salary, rent, number of children, commune code — Querying OpenFisca, the public tax and benefits rules engine — Legitimate interest. No identifier is sent: no name, no email, no address.
Creating an account — Email address, first name, last name, home city — Identifying you and letting you come back — Performance of the service you ask for by creating the account.
Saving a simulation — The contents of the simulation, including salary and rent — Finding it again later — Performance of the service, at your express request. Nothing is saved without a click from you.
Security and operation — The host''s technical logs, including the IP address — Detecting outages and abuse — Legitimate interest in keeping the service running.'),
  ('/en/privacy', 'Privacy policy', '3. What we do not do', '#3-what-we-do-not-do', 'en', 'This list matters as much as the previous one, and it can be checked: the site is written without any of these pieces.
No advertising trackers, no analytics, no social network pixels.
No resale, rental or sharing of your data for commercial purposes.
No profiling and no automated decision with legal effect: our results are indicative.
No special-category data under Article 9: no health, origin, opinion or banking data.
No precise postal address: the calculation stops at the district.'),
  ('/en/privacy', 'Privacy policy', '4. Who else sees this data', '#4-who-else-sees-this-data', 'en', 'Three providers are involved, and none receives more than its role requires.
Supabase — Accounts and saved simulations — Database and authentication — Servers in Paris (eu-west-3). Processor within the meaning of Article 28.
Vercel — Site requests, technical logs — Hosting the site and the server functions — Server functions run in Paris (cdg1). The delivery network is global; any transfers are covered by standard contractual clauses.
OpenFisca France — Salary, rent, number of children, commune code — with no identifier — Computing income tax and benefits — Public rules engine. What is sent cannot identify you.'),
  ('/en/privacy', 'Privacy policy', '5. How long we keep it', '#5-how-long-we-keep-it', 'en', 'Data kept without a reason is data you eventually lose. The periods are therefore short and tied to a use.
Simulation run without an account — Until you clear your browser storage — It never leaves your device — You can erase it at any time from your browser settings.
Account and profile — For as long as the account exists — Letting you come back — Deleted on request, together with everything attached to it.
Saved simulations — For as long as you keep them — Rereading and comparing them — Deletable one by one from your account, immediately and for good.
Technical logs — A few weeks at the host — Security and diagnosis — Periods set by the host, not used by us for anything else.'),
  ('/en/privacy', 'Privacy policy', '6. Cookies and local storage', '#6-cookies-and-local-storage', 'en', 'There is no consent banner on this site, and that is not an oversight: only strictly necessary items are stored, which exempts them under Article 82 of the French Data Protection Act.
Session cookie — Set only if you sign in — Keeping you signed in from page to page — Strictly necessary. Gone when you sign out.
Browser local storage — Simulation draft, chosen language — Not making you type your answers again — Stays on your device, never sent to a server unless you save.'),
  ('/en/privacy', 'Privacy policy', '7. Your rights', '#7-your-rights', 'en', 'You have rights of access, rectification, erasure, restriction, objection and portability over your data. Two of them are exercised directly in the interface, without writing to us: your account shows everything it holds, and each saved simulation is deleted with one click. For the others, write to us: we answer within a month.'),
  ('/en/privacy', 'Privacy policy', '8. Complaints', '#8-complaints', 'en', 'If an answer does not satisfy you, you may refer the matter to the French data protection authority: CNIL, 3 place de Fontenoy, TSA 80715, 75334 Paris Cedex 07, or online at cnil.fr.'),
  ('/en/privacy', 'Privacy policy', '9. Security', '#9-security', 'en', 'Traffic is encrypted in transit. Access to the data is partitioned in the database by policies that check, on every read and every write, that the row belongs to the signed-in person — the account id is never read from the request, only from the session cookie. No password is stored: signing in uses a single-use link sent by email.'),
  ('/en/privacy', 'Privacy policy', '10. Changes', '#10-changes', 'en', 'This policy may change with the service. The date at the top shows the current version; substantial changes will be announced on the site.'),
  ('/en/sources', 'Sources', 'insee_bpe', '#insee_bpe', 'en', 'What this source does not tell you (insee_bpe) : Records that a facility exists, not its quality, its capacity or its opening hours. A school that is counted may be full.'),
  ('/en/sources', 'Sources', 'dvf', '#dvf', 'en', 'What this source does not tell you (dvf) : What was sold, not what is for sale. Areas with too few transactions are withheld to protect statistical confidentiality.'),
  ('/en/sources', 'Sources', 'carte_loyers', '#carte_loyers', 'en', 'What this source does not tell you (carte_loyers) : Advertised rents, not rents actually paid, and at commune level: the indicator does not reach the district.'),
  ('/en/sources', 'Sources', 'education_nationale', '#education_nationale', 'en', 'What this source does not tell you (education_nationale) : Lists establishments and their addresses. Says nothing about catchment areas or your chances of getting a place.'),
  ('/en/sources', 'Sources', 'apl', '#apl', 'en', 'What this source does not tell you (apl) : Measures a supply of doctors against a demand, at commune level. It is not a guarantee of an appointment.'),
  ('/en/sources', 'Sources', 'delinquance', '#delinquance', 'en', 'What this source does not tell you (delinquance) : Offences recorded by the police and gendarmerie: depends as much on whether people report them and on police activity as on what actually happened.'),
  ('/en/coverage', 'Coverage', 'Coverage', null, 'en', 'Where WhereWise has enough data, and where results stay at commune level.
Pilot cities — Per-area (IRIS) coverage for V1.
Limited coverage — Results at commune level only.')
on conflict (source_path, heading, locale) do update set
  title = excluded.title,
  anchor = excluded.anchor,
  content = excluded.content,
  updated_at = now();
