/**
 * Generates `supabase/seed.sql` from the dictionary, so a fresh database does not
 * start with an empty assistant.
 *
 * Generated and not hand-written, for a reason this project has already paid for
 * twice. The corpus is the copy that is on our own pages, and every time a second
 * copy of that text existed it drifted: the index once held the literal
 * `{publisher}` because the page substituted the controller's name at render time,
 * and coverage headings were the body cut mid-word. A seed file maintained by hand
 * would be a third copy, and the drift is invisible — the assistant quotes the stale
 * text with a citation that looks right.
 *
 * Run it whenever the copy changes:
 *
 *     npm run seed:corpus
 *
 * `src/lib/ai/documents.test.ts` fails if the file on disk no longer matches the
 * dictionary, so forgetting is caught by the test suite rather than by a reader
 * getting an answer from last month's methodology.
 *
 * This is the cold-start path only. Re-indexing a *running* database stays the admin
 * button, which needs no secret and no deploy.
 */
import { writeFileSync } from "node:fs";
import { buildCorpus } from "../src/lib/ai/documents.ts";
import { getDictionary, locales } from "../src/lib/i18n/index.ts";

/**
 * Single-quote a value for SQL, or `null`.
 *
 * Exported so the escaping can be tested on its own. French copy is full of
 * apostrophes — "d'une ville", "l'eau", "n'est jamais" — and one that escapes wrongly
 * would end the string early and corrupt every row after it.
 */
export const sqlLiteral = (value: string | null): string =>
  value === null ? "null" : `'${value.replace(/'/g, "''")}'`;

const q = sqlLiteral;

export function buildSeedSql(): string {
  const chunks = locales.flatMap((locale) => buildCorpus(locale, getDictionary(locale)));

  const values = chunks
    .map(
      (c) =>
        `  (${q(c.source_path)}, ${q(c.title)}, ${q(c.heading)}, ${q(c.anchor)}, ` +
        `${q(c.locale)}, ${q(c.content)})`,
    )
    .join(",\n");

  const counts = locales
    .map((l) => `${chunks.filter((c) => c.locale === l).length} ${l}`)
    .join(", ");

  return `-- Generated by \`npm run seed:corpus\`. Do not edit by hand.
--
-- The assistant's corpus: the copy already published on our own pages, chunked by
-- section so a citation can name one. Written from the dictionary, which *is* the
-- source of that text, so this file cannot say something a reader does not see.
--
-- Without it a new database starts with an empty index, and the assistant then
-- answers every question about how the product works with "nothing is indexed yet".
-- That is honest but useless, and it is the state the cloud project was actually in
-- until it was noticed.
--
-- ${chunks.length} chunks (${counts}).
--
-- The NOTES directory is deliberately absent, here as everywhere: those are internal
-- engineering notes and this table is readable by anyone, so seeding them would
-- publish them.

insert into public.ai_documents (source_path, title, heading, anchor, locale, content)
values
${values}
on conflict (source_path, heading, locale) do update set
  title = excluded.title,
  anchor = excluded.anchor,
  content = excluded.content,
  updated_at = now();
`;
}

/*
  Only write when run directly. The test imports `buildSeedSql` to compare against
  the file on disk, and importing a module should never rewrite the thing being
  checked — that would make the test pass by fixing what it is meant to detect.
*/
if (process.argv[1]?.endsWith("build-corpus-seed.ts")) {
  const sql = buildSeedSql();
  writeFileSync(new URL("../supabase/seed.sql", import.meta.url), sql, "utf8");
  process.stdout.write(`supabase/seed.sql written — ${sql.split("\n").length} lines\n`);
}
